# Generated by Django 3.2.6 on 2023-04-04 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_request_requestlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.request'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
