# Generated by Django 3.2.6 on 2023-04-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230405_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlist',
            old_name='list',
            new_name='requests',
        ),
    ]
