# Generated by Django 3.2.6 on 2023-04-05 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230405_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlist',
            name='requests',
        ),
        migrations.AddField(
            model_name='request',
            name='request_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.requestlist'),
        ),
    ]
