# Generated by Django 3.2.6 on 2023-04-09 07:17

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230405_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='media',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Media cover'),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(null=True, upload_to=home.models.media_file_storage, verbose_name='Media location'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
