# Generated by Django 3.2.6 on 2023-04-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230409_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='multi_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.multimedia'),
        ),
        migrations.AlterField(
            model_name='media',
            name='single_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.singlemedia'),
        ),
    ]
