# Generated by Django 3.2.6 on 2023-04-09 08:20

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230409_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.media_file_storage, verbose_name='Media cover'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=home.models.media_file_storage, verbose_name='Media location'),
        ),
    ]
