# Generated by Django 3.2.6 on 2023-04-09 08:53

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230409_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.multimedia_file_storage),
        ),
        migrations.AlterField(
            model_name='videoplaylist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.videoplaylist_file_storage),
        ),
    ]
