# Generated by Django 3.2.6 on 2023-04-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230409_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlemedia',
            name='user_wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.wishlist'),
        ),
        migrations.AlterField(
            model_name='videoplaylist',
            name='user_wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.wishlist'),
        ),
    ]
